export const INSURANCES = [
  "Private",
  "AFRICA MEDILINK",
  "AGAHOZO SHALOM YOUTH VILLAGE",
  "ALLIANZ",
  "AMREF Flying Doctors",
  "Angola Embassy",
  "ASA MICROFINANCE",
  "ASCOMA",
  "ASSEMBLE INSURANCE TANZANIA LTD",
  "ASSEMBLE TZ",
  "AXA Assistance",
  "BNR",
  "BRITAM Insurance",
  "BROWN PLANTATION RWANDA (BPR)",
  "BRUSSELS",
  "BUGAMBIRA MINING LTD",
  "BUPA",
  "CHINA ROAD",
  "CIC GENERAL",
  "CIGNA",
  "CLA Christian Life Assembly",
  "DAVIS&SHIRTLIFF RWANDA LTD",
  "Deva",
  "DREAM MEDICAL CENTER",
  "EDEN CARE INSURANCE",
  "Equity Bank Rwanda",
  "ERNEST & YOUNG",
  "Excella School",
  "FPR",
  "HENNER",
  "Heritage Insurance Company",
  "Hope & Homes for Children",
  "INYANGE INDUSTRIE LTD",
  "IOM",
  "ITM AFRICA LTD",
  "JUBILEE DENTAL CLINIC",
  "KICS",
  "King Faisal Hospital",
  "La Croix du Sud",
  "LAWYERS OF HOPE",
  "MAGERWA",
  "MIS/UR INSURANCE",
  "MMI",
  "MSH International Insurance",
  "OLD MUTUAL",
  "PEACE Plan",
  "PINEDA DENTAL",
  "Polyclinique du Plateau",
  "PRICE WATER HOUSE (PWC)",
  "PRIME INSURANCE LTD",
  "Private Sector Federation",
  "Radiant Insurance Company",
  "Rwanda Bar Association",
  "Rwanda Events Group",
  "RWANDA MILITARY HOSPITAL",
  "Rwanda Social Security Board",
  "Rwanda Trading Company",
  "RWANDAIR MEDICAL",
  "SAHAM INSURANCE",
  "SANLAM",
  "SEE FAR HOUSING",
  "SGF Special Guarantee Fund",
  "SINELAC",
  "SONARWA",
  "SWISS EMBASSY",
  "UBF(Ubuzima Bwiza Fundation)",
  "UNHCR",
  "UR CMHSBD LTD",
  "Urwego Opportunity",
  "VINE PHARMACY"
];
