'use strict';

/**
 * System Permission Modules Definition
 */
const MODULES = [
  { name: 'cancellations',     display: 'Cancellation Requests', actions: ['view','create','edit','review','approve','reject','delete'] },
  { name: 'refunds',           display: 'Refund Requests',       actions: ['view','create','edit','review','approve','reject','delete'] },
  { name: 'results_transfer',  display: 'Result Transfers',      actions: ['view','create','edit','review','approve','reject','delete'] },
  { name: 'incident_reports',  display: 'Incident Reports',      actions: ['view','create','edit','review','approve','delete'] },
  { name: 'user_management',   display: 'User Management',       actions: ['view','create','edit','delete'] },
  { name: 'audit_logs',        display: 'Audit Logs',            actions: ['view'] },
  { name: 'reports',           display: 'Reports & Insights',    actions: ['view','download'] },
  { name: 'staff_performance', display: 'Staff Performance',     actions: ['view','create'] },
  { name: 'clinical_observation', display: 'Clinical Observation', actions: ['view','create','edit','review','approve'] },
  { name: 'shifts',              display: 'Shift Management',      actions: ['view','create','edit','review','delete'] },
  { name: 'feedbacks',           display: 'Internal Feedback',     actions: ['view','delete'] },

  // ── Added: modules that existed as real, navigable app sections but had no
  // row in the Access Control Matrix at all -- defaults below mirror each
  // area's existing hardcoded authorizeRoles()/allowedRoles lists exactly, so
  // adding these does not change anyone's access on its own.
  { name: 'safety',           display: 'Safety Management (Risk/Infection Control)', actions: ['view','create','delete'] },
  { name: 'inventory',        display: 'Central Store & Master Inventory',           actions: ['view','create','edit','delete'] },
  { name: 'daily_stock',      display: 'Daily Stock Checkup',                        actions: ['view','edit'] },
  { name: 'procurement',      display: 'Procurement & Purchase Orders',              actions: ['view','create','edit'] },
  { name: 'ai_insights',      display: 'AI Insights',                                actions: ['view','download'] },
  { name: 'revenue_leakage',  display: 'Revenue Leakage Tracker',                    actions: ['view','create','edit','delete'] },
  { name: 'compliance',       display: 'Compliance Portal',                          actions: ['view','create','edit','delete'] },
  { name: 'it_support',       display: 'IT Support Hub',                             actions: ['view','create','edit','delete'] },
  { name: 'patients',         display: 'Patient Records & Prescriptions',            actions: ['view','create'] },
  { name: 'imaging',          display: 'Imaging (Radiology) Portal',                 actions: ['view','create','edit','acquire','report','verify','delete'] },
];

/**
 * Default Role Permissions (System Standards)
 */
const ROLE_DEFAULTS = {
  admin: {
    cancellations:    { view:1, create:0, edit:1, review:0, approve:0, reject:0 },
    refunds: { view:1, create:0, edit:1, review:0, approve:0, reject:0 },
    results_transfer: { view:1, create:1, edit:1, review:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:0 },
    user_management: { view:1, create:1, edit:1, delete:1 },
    audit_logs: { view:1 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:1 },

    shifts:           { view:1, create:1, edit:1, review:1, delete:1 },
    feedbacks:        { view:0, delete:0 },
    safety:           { view:1, create:1, delete:1 },
    inventory:        { view:1, create:1, edit:1, delete:1 },
    daily_stock:      { view:1, edit:1 },
    procurement:      { view:1, create:1, edit:1 },
    ai_insights:      { view:1, download:1 },
    revenue_leakage:  { view:1, create:1, edit:1, delete:1 },
    compliance:       { view:1, create:1, edit:1, delete:1 },
    it_support:       { view:1, create:1, edit:1, delete:1 },
    patients:         { view:1, create:0 },
    imaging:          { view:1, create:1, edit:1, acquire:0, report:0, verify:0, delete:1 },
  },
  it_officer: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:0 },
    user_management: { view:1, create:1, edit:1, delete:1 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:0, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    it_support:       { view:1, create:1, edit:1, delete:1 },
    patients:         { view:1, create:0 },
  },
  coo: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:1, reject:1 },
    incident_reports: { view:1, create:0, edit:0, approve:1 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },
    clinical_observation: { view:1, create:0, edit:0, review:0, approve:0 },

    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:1, delete:1 },
    safety:           { view:1, create:1, delete:1 },
    ai_insights:      { view:1, download:1 },
    revenue_leakage:  { view:1, create:1, edit:1, delete:1 },
    compliance:       { view:1, create:1, edit:1, delete:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
    imaging:          { view:1, create:0, edit:0, acquire:0, report:0, verify:0, delete:0 },
  },
  deputy_coo: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:1, reject:1 },
    incident_reports: { view:1, create:0, edit:0, approve:1 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },

    shifts:           { view:1, create:1, edit:1, review:1, delete:0 },
    feedbacks:        { view:1, delete:1 },
    safety:           { view:1, create:1, delete:1 },
    inventory:        { view:1, create:1, edit:1, delete:1 },
    procurement:      { view:1, create:1, edit:1 },
    ai_insights:      { view:1, download:1 },
    revenue_leakage:  { view:1, create:1, edit:1, delete:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
    imaging:          { view:1, create:0, edit:0, acquire:0, report:0, verify:0, delete:0 },
  },
  chairman: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:0 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:0 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:0, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    ai_insights:      { view:1, download:1 },
    revenue_leakage:  { view:1, create:1, edit:1, delete:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  sales_manager: {
    cancellations:    { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },

    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:0, delete:0 },
    ai_insights:      { view:1, download:1 },
    revenue_leakage:  { view:1, create:1, edit:1, delete:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  cashier: {
    cancellations:    { view:1, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:1, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:1, create:1, edit:1, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  principal_cashier: {
    cancellations:    { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:1, reject:1 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:0 },
    staff_performance: { view:1, create:1 },

    shifts:           { view:1, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    ai_insights:      { view:1, download:0 },
    revenue_leakage:  { view:1, create:1, edit:1, delete:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  customer_care: {
    cancellations:    { view:1, create:1, edit:0, approve:0, reject:0 },
    refunds: { view:1, create:1, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:1, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:1, create:1, edit:1, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  lab_team_lead: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:0, edit:1, approve:1, reject:1 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:0, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  consultant: {
    cancellations:    { view:1, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:1, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:0, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:0 },
    staff_performance: { view:0, create:0 },
    clinical_observation: { view:1, create:0, edit:0, review:0, approve:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    inventory:        { view:1, create:0, edit:0, delete:0 },
    daily_stock:      { view:1, edit:0 },
    ai_insights:      { view:1, download:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  operations_staff: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:0, delete:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  pa: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:0, create:0 },
    clinical_observation: { view:1, create:0, edit:0, review:0, approve:0 },
    shifts:           { view:1, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    daily_stock:      { view:1, edit:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  staff: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:0, create:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  hsfp: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:0, edit:0, review:0, approve:1, delete:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:0, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    safety:           { view:1, create:1, delete:1 },
    compliance:       { view:1, create:1, edit:1, delete:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  nurse: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:1, create:0 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:0 },

    shifts:           { view:1, create:1, edit:1, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    inventory:        { view:1, create:1, edit:1, delete:1 },
    daily_stock:      { view:1, edit:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  'chef-nurse': {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:1 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:1, create:1 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:1 },
    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:1, delete:0 },
    inventory:        { view:1, create:1, edit:1, delete:1 },
    daily_stock:      { view:1, edit:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  'stock-manager': {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:0, create:0 },
    clinical_observation: { view:1, create:0, edit:0, review:0, approve:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    inventory:        { view:1, create:1, edit:1, delete:1 },
    daily_stock:      { view:1, edit:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },
  doctor: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:0, create:0 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:1 },
    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    inventory:        { view:1, create:0, edit:0, delete:0 },
    daily_stock:      { view:1, edit:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:1 },
  },
  medical_director: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:1 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:0, create:0 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:1 },
    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:1, delete:1 },
    inventory:        { view:1, create:0, edit:0, delete:0 },
    daily_stock:      { view:1, edit:0 },
    ai_insights:      { view:1, download:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:1 },
    imaging:          { view:1, create:0, edit:0, acquire:0, report:1, verify:1, delete:0 },
  },
  'procurement-manager': {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:0, create:0 },
    clinical_observation: { view:1, create:0, edit:0, review:0, approve:0 },
    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
    inventory:        { view:1, create:1, edit:1, delete:1 },
    daily_stock:      { view:1, edit:1 },
    procurement:      { view:1, create:1, edit:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
  },

  // ── Imaging (Radiology) Department roles ──────────────────────────────────
  // Modality is a study/shift attribute, not a role: a "CT Radiographer" is a
  // radiographer working the CT station. Sonographers both acquire and report
  // their own ultrasound studies (per the department task sheet), so they hold
  // the `report` action; plain radiographers acquire only.
  radiographer: {
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:1, create:0 },
    shifts:           { view:1, create:0, edit:0, review:0, delete:0 },
    inventory:        { view:1, create:1, edit:0, delete:0 },
    daily_stock:      { view:1, edit:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
    imaging:          { view:1, create:1, edit:1, acquire:1, report:0, verify:0, delete:0 },
  },
  sonographer: {
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:1, create:0 },
    shifts:           { view:1, create:0, edit:0, review:0, delete:0 },
    inventory:        { view:1, create:1, edit:0, delete:0 },
    daily_stock:      { view:1, edit:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
    imaging:          { view:1, create:1, edit:1, acquire:1, report:1, verify:0, delete:0 },
  },
  radiologist: {
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:1, create:0 },
    shifts:           { view:1, create:0, edit:0, review:0, delete:0 },
    inventory:        { view:1, create:0, edit:0, delete:0 },
    daily_stock:      { view:1, edit:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
    imaging:          { view:1, create:0, edit:1, acquire:0, report:1, verify:1, delete:0 },
  },
  imaging_receptionist: {
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:1, create:0 },
    shifts:           { view:1, create:0, edit:0, review:0, delete:0 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:1 },
    imaging:          { view:1, create:1, edit:1, acquire:0, report:0, verify:0, delete:0 },
  },
  imaging_manager: {
    incident_reports: { view:1, create:1, edit:1, approve:1 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:1, create:1 },
    shifts:           { view:1, create:1, edit:1, review:1, delete:0 },
    inventory:        { view:1, create:1, edit:1, delete:1 },
    daily_stock:      { view:1, edit:1 },
    it_support:       { view:1, create:1 },
    patients:         { view:1, create:0 },
    imaging:          { view:1, create:1, edit:1, acquire:1, report:1, verify:1, delete:1 },
  },
};

module.exports = {
  MODULES,
  ROLE_DEFAULTS,
};
