'use strict';

/**
 * System Permission Modules Definition
 */
const MODULES = [
  { name: 'cancellations',     display: 'Cancellation Requests', actions: ['view','create','edit','review','approve','reject','delete'] },
  { name: 'refunds',           display: 'Refund Requests',       actions: ['view','create','edit','review','approve','reject','delete'] },
  { name: 'results_transfer',  display: 'Result Transfers',      actions: ['view','create','edit','review','approve','reject','delete'] },
  { name: 'incident_reports',  display: 'Incident Reports',      actions: ['view','create','edit','review','approve','delete'] },
  { name: 'user_management',   display: 'User Management',       actions: ['view','create','edit','delete'] },
  { name: 'audit_logs',        display: 'Audit Logs',            actions: ['view'] },
  { name: 'reports',           display: 'Reports & Insights',    actions: ['view','download'] },
  { name: 'staff_performance', display: 'Staff Performance',     actions: ['view','create'] },
  { name: 'clinical_observation', display: 'Clinical Observation', actions: ['view','create','edit','review','approve'] },
  { name: 'shifts',              display: 'Shift Management',      actions: ['view','create','edit','review','delete'] },
  { name: 'feedbacks',           display: 'Internal Feedback',     actions: ['view','delete'] },
];

/**
 * Default Role Permissions (System Standards)
 */
const ROLE_DEFAULTS = {
  admin: {
    cancellations:    { view:1, create:0, edit:1, review:0, approve:0, reject:0 },
    refunds: { view:1, create:0, edit:1, review:0, approve:0, reject:0 },
    results_transfer: { view:1, create:1, edit:1, review:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:0 },
    user_management: { view:1, create:1, edit:1, delete:1 },
    audit_logs: { view:1 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:1 },

    shifts:           { view:1, create:0, edit:1, review:1, delete:1 },
    feedbacks:        { view:0, delete:0 },
  },
  it_officer: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:0 },
    user_management: { view:1, create:1, edit:1, delete:1 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:0, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  coo: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:1, reject:1 },
    incident_reports: { view:1, create:0, edit:0, approve:1 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:1 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },

    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:1, delete:1 },
  },
  deputy_coo: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:1, reject:1 },
    incident_reports: { view:1, create:0, edit:0, approve:1 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:1 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },

    shifts:           { view:1, create:0, edit:1, review:1, delete:0 },
    feedbacks:        { view:1, delete:1 },
  },
  chairman: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:0 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:0 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:0, edit:0, approve:1 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  sales_manager: {
    cancellations:    { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:1 },
    staff_performance: { view:1, create:1 },

    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  cashier: {
    cancellations:    { view:1, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:1, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:0, create:1, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  principal_cashier: {
    cancellations:    { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, review:1, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:1, reject:1 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:0 },
    staff_performance: { view:1, create:1 },

    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  customer_care: {
    cancellations:    { view:1, create:1, edit:0, approve:0, reject:0 },
    refunds: { view:1, create:1, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:1, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:0, create:1, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  lab_team_lead: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:0, edit:1, approve:1, reject:1 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:0, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  consultant: {
    cancellations:    { view:1, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:1, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:0, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:1, download:0 },
    staff_performance: { view:0, create:0 },
    clinical_observation: { view:1, create:0, edit:0, review:0, approve:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  operations_staff: {
    cancellations:    { view:1, create:0, edit:0, approve:1, reject:1 },
    refunds: { view:1, create:0, edit:0, approve:1, reject:1 },
    results_transfer: { view:1, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:1, create:0 },

    shifts:           { view:1, create:0, edit:0, review:1, delete:0 },
    feedbacks:        { view:0, delete:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  staff: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds: { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:0, approve:0 },
    user_management: { view:0, create:0, edit:0, delete:0 },
    audit_logs: { view:0 },
    reports: { view:0, download:0 },
    staff_performance: { view:0, create:0 },
  },
  hsfp: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:0, edit:0, review:0, approve:1, delete:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:0, create:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  nurse: {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:0, download:0 },
    staff_performance:{ view:1, create:0 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:0 },

    shifts:           { view:0, create:1, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  'chef-nurse': {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:1, create:1, edit:1, approve:1 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:1, create:1 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:1 },
  },
  reviewer: {
    cancellations:    { view:1, create:1, edit:1, review:1, approve:1, reject:1, delete:1 },
    refunds:          { view:1, create:1, edit:1, review:1, approve:1, reject:1, delete:1 },
    results_transfer: { view:1, create:1, edit:1, review:1, approve:1, reject:1, delete:1 },
    incident_reports: { view:1, create:1, edit:1, review:1, approve:1, delete:1 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:1, create:1 },
    clinical_observation: { view:1, create:1, edit:1, review:1, approve:1 },

    shifts:           { view:1, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
  'stock-manager': {
    cancellations:    { view:0, create:0, edit:0, approve:0, reject:0 },
    refunds:          { view:0, create:0, edit:0, approve:0, reject:0 },
    results_transfer: { view:0, create:0, edit:0, approve:0, reject:0 },
    incident_reports: { view:0, create:0, edit:0, approve:0 },
    user_management:  { view:0, create:0, edit:0, delete:0 },
    audit_logs:       { view:0 },
    reports:          { view:1, download:1 },
    staff_performance:{ view:0, create:0 },
    clinical_observation: { view:1, create:0, edit:0, review:0, approve:0 },

    shifts:           { view:0, create:0, edit:0, review:0, delete:0 },
    feedbacks:        { view:0, delete:0 },
  },
};

module.exports = {
  MODULES,
  ROLE_DEFAULTS,
};
